clone_folder: c:\projects\azure-sdk-for-net

environment:
  access_token:
    secure: JWSy9tPo2eoTYpPQplvokf4IiVk6onNBbWwAs6nNWWyQ2JaO+MRAg/QzbJnTjpUm

install:
  - cinst docfx

before_build:
  - cd ..
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "vscopbld@microsoft.com"
  - git config --global user.name "OpenPublishBuild"
  - git clone -q --branch=master https://github.com/dotnet/coreclr.git
  - git clone -q --branch=master https://github.com/Visual-Studio-China/core-docs.git
  - cd core-docs
  
build_script:
  - docfx metadata
  
on_success:
  - git add .
  - git commit -m "CI Updates"
  - git push origin master
